on:
    push:
        tags:
            - "v*"

name: Publish Cookie Clicker Stable

jobs:
    create-release:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Get current time
              uses: srfrnk/current-time@master
              id: current-time
              with:
                format: DD.MM.YYYY HH:mm [UTC]
            - name: Checkout code
              uses: actions/checkout@v2
            - name: 'Get Previous tag'
              id: previoustag
              uses: "WyriHaximus/github-action-get-previous-tag@v1"
            - name: read changelog file
              uses: juliangruber/read-file-action@v1
              id: changelog
              with:
                path: ./changelog.md
            - name: Split Changelog
              id: split
              uses: rishabhgupta/split-by@v1
              with:
                string: ${{ steps.changelog.outputs.content }}
                split-by: "========"
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                name: release ${{ steps.previoustag.outputs.tag }} --- ${{ steps.current-time.outputs.formattedTime }}
                tag: ${{ steps.previoustag.outputs.tag }}
                body: |
                    ![GitHub release (by tag)](https://img.shields.io/github/downloads/LetsFinishSchool/CookieClicker/${{ steps.previoustag.outputs.tag }}/total)
                    ${{ steps.split.outputs._0}}
    build:
        needs: create-release
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest , macOS-latest] # doesn't work for some reason
            fail-fast: false
        name: Build and publish ${{ matrix.os }}
        steps:
            - name: Git checkout
              uses: actions/checkout@v2
            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                java-version: '14'
                distribution: 'zulu'#use zulu because temurin doesn't support java 15
                cache: 'gradle'
            - name: Echo JAVA_HOME
              run: echo $JAVA_HOME
            - name: Verify Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1
            - name: Execute build
              run: ./gradlew --info --stacktrace :desktop:dist
            - name: Execute runtime
              run: ./gradlew --info --stacktrace :desktop:runtime
            - name: Execute jpackage
              run: ./gradlew --info --stacktrace :desktop:jpackage
            - name: Upload DMG as an artifact
              uses: softprops/action-gh-release@v1
              with:
                files: desktop/build/jpackage/*.dmg
            - name: Upload EXE as an artifact
              uses: softprops/action-gh-release@v1
              with:
                files: desktop/build/jpackage/*.exe
            - name: Upload MSI as an artifact
              uses: softprops/action-gh-release@v1
              with:
                files: desktop/build/jpackage/*.msi
            - name: Upload DEB as an artifact
              uses: softprops/action-gh-release@v1
              with:
                files: desktop/build/jpackage/*.deb
            - name: Upload RPM as an artifact
              uses: softprops/action-gh-release@v1
              with:
                files: desktop/build/jpackage/*.rpm
    jar:
        needs: create-release
        runs-on: ubuntu-latest
        name: upload jar and app-image
        steps:
            - name: Git checkout
              uses: actions/checkout@v2
            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                java-version: '14'
                distribution: 'zulu'#use zulu because temurin doesn't support java 15
                cache: 'gradle'
            - name: Echo JAVA_HOME
              run: echo $JAVA_HOME
            - name: Verify Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1
            - name: Execute build
              run: ./gradlew --info --stacktrace :desktop:build
            - name: Execute runtime
              run: ./gradlew --info --stacktrace :desktop:runtime
            - name: Execute jpackage
              run: ./gradlew --info --stacktrace :desktop:jpackage
            - name: Upload Jar as an artifact
              uses: softprops/action-gh-release@v1
              with:
                files: desktop/build/libs/*.jar
            - name: Upload App Images as an artifact
              uses: softprops/action-gh-release@v1
              with:
                files: desktop/build/distributions/*
